### ISSUE TITLE
event cmd runjs - including already written scripts

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#119]
In the runjs cmd dialog. It is possible to include script files from the project?

Like in php:
include "script1.js"

Maybe in the editor?
Game.Include("script1.js")

That you are able to write your own libraries, and use them everywhere?

**Comment by tommycli** [comment]
You've convinced me this is an important feature. I'll work on this next.

I've already implemented includeFile(...) in globals.js. Now I will add an EventCmd for this.
