### ISSUE TITLE
[Bug] Music stops in boss battle

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#191]
So i requested that you can add music in a bossbattle and i am happy you added the music only if i play it and you battle against a boss the song stops please fix it
already thanks
-linkingit

**Comment by tommycli** [comment]
This works for me.

Can you send me a simple sample project where this fails? rpgboss@keepword.com

**Comment by ravedragon** [comment]
it does? lol must be some people ;p

**Comment by linkigit** [comment]
simple sample project? what is that? Because it still don't works for me

**Comment by ravedragon** [comment]
he wants you to zip ur project folder and send to him to get the idea or data.

**Comment by linkigit** [comment]
Oh ok ty will do tommorow must sleep now

**Comment by linkigit** [comment]
done hopefully it comes good on

**Comment by tommycli** [comment]
Okay I understand what you mean now.

You mean that the music you play stops DURING the battle.

Yes, that is not finished yet. I will work on that for the next release. Thanks.

**Comment by linkigit** [comment]
ty
