### ISSUE TITLE
if command

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#198]
The if command.

What it should can...

* compare of variables (global, local)
* compare of event characteristics ( position, and all other stuff from rpg maker)
* compare of mouse characteristics (#197)
* compare of hero characteristics ( hp, mp, all other stuff from rpg maker)

Let the user decide if theres a else branch with a checkbox.

maybe much more.

**Comment by tommycli** [comment]
It uses the same list of conditions available in Event Conditions. File a separate tickets for new requested condition types.

**Comment by tommycli** [comment]
These two commits show the process of adding a complex EventCmd... for the next person to take it over:

https://github.com/rpgboss/rpgboss/commit/874e04b7c32ae43b4185457ff6081aed49e0fbb1
https://github.com/rpgboss/rpgboss/commit/c7a50cd6dcdf560d177f8b4b2935494473e5c924
