### ISSUE TITLE
Mp beyond the limit!

### ISSUE THREAD

**Issue by ravedragon** [rpgboss/rpgboss#210]
picture this lol
![export35](https://cloud.githubusercontent.com/assets/8285836/5690725/e5aea850-9853-11e4-8999-017a3241ef9a.jpg)
![export36](https://cloud.githubusercontent.com/assets/8285836/5690726/e7e12f08-9853-11e4-868f-692a9a028f93.jpg)

**Comment by tommycli** [comment]
lol epic fail

good bug report
