### ISSUE TITLE
[Suggestion] Quests

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#217]
I miss quests is like all the rpgs have quests and this tool haven't a quest system shall be nice if they had one like if you create a npc you shall add something like quest and you can choose the goal (for example give a egg to him) and then add a reward if you completed the quest or something like a main quest like beat 12 zombies to continue to the boss battle
already thanks
-linkingit

**Comment by ravedragon** [comment]
i assume you mean something like a quest reminder in menus.
but other then that, you can do all of those with if conditions and variables.

**Comment by linkigit** [comment]
yeah like a reminder but how do i use the quest?whatever will ask that in the forums.

**Comment by tommycli** [comment]
Yeah there will be no pre-built quest system.

Maybe someone can write some Event Classes or custom scripts to manage this.
