### ISSUE TITLE
[SUGGESTION] An option to change the language

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#219]
Hi,

I have an idea, why you don't implement an button (or combobox) to change the language.

Exemple: i am in my french computer and i wan't to use RPGBoss in English, Actually i can't.

So good works for this version

**Comment by tommycli** [comment]
Are you on Linux? Try using this: https://wiki.archlinux.org/index.php/locale#Launch_application_with_different_locale_from_terminal
Rather than adding more UI, we should use environment variables to allow users to launch with a different locale than their system setting
