### ISSUE TITLE
Play freezes everything

### ISSUE THREAD

**Issue by AnonymousPerson** [rpgboss/rpgboss#220]
I have been trying your program for a while- best free (and legal) RPG maker I've seen by the way, most split editor and engine and never get done, but you guys did and have frequent updates, sorry I'm rambling- but recently whenever I click the play button everything freezes and I have to exit. I usually delete the old version and download the new one while keeping the same folder. Would that cause the problem?

**Comment by ravedragon** [comment]
if you say recently, it must be something related to a event you made? like run once, then increment state( uncheck that if you had 1 state). or a removed resource that was still in some of the maps.

**Comment by AnonymousPerson** [comment]
I edited the increment states and searched the resources. Everything I am using is accounted for, but it is still freezing. Even when I make a new game that freezes.

**Comment by ravedragon** [comment]
i see, i suggest to zip your project folder and send to rpgboss@keepword.com and have the developer have a look. also suggest you use the old rpgboss you used for now until he pinpoint.. title email and explain what it for lol

**Comment by tommycli** [comment]
When you press 'Play Now', does it get to the New Game menu?

If it doesn't, it's probably not an issue with your game itself.

Perhaps try moving your game project folder to a simple path? Like C:\testgame? Does that work?

**Comment by AnonymousPerson** [comment]
I can't save it to C:\ because I don't have a laptop of my own. But saving it to E:\ worked. Thank you!

**Comment by ravedragon** [comment]
i see his solution solved yours ill close this lol
