### ISSUE TITLE
[BUG] Can't add Monster in the party

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#226]
hi guys,

i have create a monster and i can't add it in the enemis party.

This is an screenshoots
![bug](https://cloud.githubusercontent.com/assets/923600/5792500/c7bfd5a8-9f1a-11e4-8f4b-b8d9eaef8ef3.PNG)

Regards

**Comment by ravedragon** [comment]
actually look at scroll bar. somehow it needs to be stretched

**Comment by Caranille** [comment]
Yes, i have see it, but when i choose an monster and i click on the ADD Buton the screen is black (how like the picture)

**Comment by ravedragon** [comment]
ah i see this is the latest bug huh.

**Comment by ravedragon** [comment]
use 0.6.0 for now.

**Comment by Caranille** [comment]
Hello, i re open this issue because and other bug exist.

If you cick on Delete and just after Add button RPGBoss freeze.
I think the engine lost the focus on the monster choice.

**Comment by ravedragon** [comment]
but it not the same bug? as above?

**Comment by ravedragon** [comment]
seems to work for me, you got any example?
