### ISSUE TITLE
[Bug] game freezes

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#230]
My game freeze after i got telported to another map and on the other map try to open my inventory!

**Comment by ravedragon** [comment]
i would question if the event is correctly teleporting to a map that exist, and maybe in the inventory if the item exist oo

**Comment by linkigit** [comment]
sorry i don't understand you i have created on the starting map that you need to choose your name gender and class if you choose that you get teleported to the other map

**Comment by linkigit** [comment]
oh already fixed i had too many characters

**Comment by ravedragon** [comment]
i see thanks for information. there always something like that,
