### ISSUE TITLE
Sugestions

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#233]
Hi please don't close this topic too fast because i want to update it if i have more suggestions before i make 800 topics
1. Update te enemy stats right now for example is the Max attack stats 50 but for the played character it is 100+ and i need more then 50 attack fot the boss battles
2. Idk or it already is in it or not but that you can let npcs wander

**Comment by Caranille** [comment]
Your request is very strong. I talkt it with tommy in the evening

**Comment by linkigit** [comment]
ok ty

**Comment by ravedragon** [comment]
next release the limit has been raised. for random movement, it been suggested. just no date for add.

**Comment by linkigit** [comment]
ok thx!

**Comment by tommycli** [comment]
Will be in next release. Re-open if still an issue.
