### ISSUE TITLE
[IDEA] Create an MAP WORLD

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#235]
Hello everybody.

I have an problem. I want to create an big map how life the last final fatasy generation but i can't because the Height is 40 and Width is 30.

Can you unblock it for create an big map (500 * 500)

Regards, jeremy

**Comment by ravedragon** [comment]
that is weird because you can increase the size , and 40x30 is just a default. and the map size can be upped from map properties?
![export73](https://cloud.githubusercontent.com/assets/8285836/5881649/5880daee-a2f7-11e4-9ed8-8fa8805dcf41.jpg)

**Comment by Caranille** [comment]
The problem is that when I want to exchange as soon as I click OK or validate it calls the default number

**Comment by Caranille** [comment]
Okay... I'm stupid, i close this issue

**Comment by ravedragon** [comment]
oh wrong spot? oo

**Comment by Caranille** [comment]
no i'm stupid because your solution work. i have chosse 999 and the maximum is 500 :p
