### ISSUE TITLE
[Bug] Heal/Damage

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#236]
Hey if i use the heal/damage command it don't heal or damage my team or a specified person

**Comment by ravedragon** [comment]
seems to work for me . what you do.

**Comment by linkigit** [comment]
I created with another tileset a bed where you can go trough and made a event in it and if you go in the bed you go to sleep and your party will be healed only that don't works for me he still haves the same health as before the heal event

**Comment by ravedragon** [comment]
is it set trigger touch by player?

**Comment by linkigit** [comment]
yeah

**Comment by linkigit** [comment]
but i made something like a inn too with button and that didn't work too

**Comment by ravedragon** [comment]
very odd. let me create a screenshot and show you if it the same you did.

**Comment by ravedragon** [comment]
after testing the latest version it is bugged lol
![healbug](https://cloud.githubusercontent.com/assets/8285836/5995135/a0a9fb26-aa3f-11e4-9bc3-e4be199a95a0.jpg)
