### ISSUE TITLE
[BUG] An probleme with UTF-8

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#248]
Hi guys,

i have begin my game but when i close the project and i opened it i have an eroor of the char (View screen)
![erreur2](https://cloud.githubusercontent.com/assets/923600/5989983/5be62ba2-a99c-11e4-9882-483ac6c6293b.png)

**Comment by ravedragon** [comment]
Ah confirmed bug, after saving project the text will try to convert into ansi. is that a bug? lol
![export85](https://cloud.githubusercontent.com/assets/8285836/5995160/71e59024-aa40-11e4-85aa-c3f9280d9dc3.jpg)
![export86](https://cloud.githubusercontent.com/assets/8285836/5995162/74ec3f52-aa40-11e4-9922-1746b3cd4b5e.jpg)
