### ISSUE TITLE
Mac Right-Click/Ctrl+Click Not Working

### ISSUE THREAD

**Issue by SkittishSloth** [rpgboss/rpgboss#252]
I posted about this in the forum and was referred over here; I'm not able to really do much of anything outside of playing around with the initial map.  I see lots of stuff about right-clicking on different things, but I'm on a Mac -- normally this converts to just control-clicking, but that has no effect anywhere.  I've tried various combinations: ctrl+click, command+click, alt/option+click, and different combinations of those, with no results.

Am I just missing something?  I would've thought the JVM handled this automatically, but maybe not?

I'm using the release from today (0.6.5); pretty recent Java install (I know I have 8 on my machine, but not sure what this would run under by default), and OS 10.9.5.  I'm a Java dev, so no need to be gentle if you need more info -- I might not know off hand how to get it, but I can figure it out pretty quick I'm sure.

Awesome app btw!

**Comment by tommycli** [comment]
Yeah we have the context menus hooked up the the right click specifically.

There must be some generic context menu event that maps to right-click on PC and control-click on Mac. I will look into it. thanks for the report!

**Comment by tommycli** [comment]
https://github.com/rpgboss/rpgboss/blob/master/editor/src/main/scala/rpgboss/editor/dialog/CommandBox.scala#L83

That is an example of what we do in the code. I see now that it probably isn't the best idea, as it doesn't accommodate Mac at all.

**Comment by tommycli** [comment]
On a side note, would it be better if the Mac distribution was packaged into a .app package?

**Comment by tommycli** [comment]
Okay i think I get it. Probably just need to change all instances of:

`if (e.peer.getButton() == MouseEvent.BUTTON3) `

to

`if (e.peer.getButton() == MouseEvent.BUTTON3 || e.isControlDown())` 

in the code.

**Comment by tommycli** [comment]
Feel free to submit a patch, or you can wait for me to get around to it.

**Comment by SkittishSloth** [comment]
Thanks for the quick turnaround!  I'd gladly do the patch myself, but I'm completely clueless with scala and I'd either end up borking something or taking longer than just waiting for you to do it.  I can wait :)  Thanks!
