### ISSUE TITLE
[Bug] freeze

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#262]
If i test my game the game shows up for 1 - 5 seconds and then disapears but the music from the title screen still plays.

**Comment by ravedragon** [comment]
I suggest you backtrack your stuff, like deleted events, event with missing state or that doesn't exist. what you did before this happen?, if possible can you provide the screenshot of the command prompt

**Comment by linkigit** [comment]
Hope this screenshot is good
![bandicam 2015-02-09 10-00-39-721](https://cloud.githubusercontent.com/assets/10259891/6103282/aab63ac2-b042-11e4-80c0-bd455d54e656.jpg)

**Comment by ravedragon** [comment]
is this the latest 0.6.5? there a lot of code change so suggest checking every event resetting it.
or can you try out if 0.6.4 it still working.

**Comment by linkigit** [comment]
I tried to use 0.6.4 but that didn't work too and what do you mean with event resetting?

**Comment by ravedragon** [comment]
hmm can you try changing the msgfont to veremono.ttf and tell me the changes.
![export90](https://cloud.githubusercontent.com/assets/8285836/6110842/660a4a84-b039-11e4-8d4d-91b8535c1e1f.png)

**Comment by linkigit** [comment]
it works thx
