### ISSUE TITLE
Sleep CMD does nothing

### ISSUE THREAD

**Issue by AnonymousPerson** [rpgboss/rpgboss#269]
Is it supposed to fade the screen or heal? Because for me it does neither.

**Comment by ravedragon** [comment]
for now it just delays the events for certain duration

**Comment by AnonymousPerson** [comment]
I see. Thanks for the quick reply! For now I am faking the effect with the teleport and heal commands.

**Comment by hendrik-weiler** [comment]
If you use the javascript cmd you can just write
```
// FadeOut
game.setTransition(1, 0.4);
// FadeIn
game.setTransition(0, 1.0);
```

**Comment by tommycli** [comment]
Maybe we should rename Sleep to 'Thread Sleep' or 'Script Wait' or 'Wait...' or something to prevent this confusion.

**Comment by hendrik-weiler** [comment]
You can also use the tint screen cmd to do a simple fadein, fadeout.
