### ISSUE TITLE
game over cmd finializing - to title screen cmd bug

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#276]
The game over cmd needs to be finalized. I dont know how to that.

https://github.com/rpgboss/rpgboss/pull/275

**Comment by hendrik-weiler** [comment]
The choice back to title screen does not working. I dont know whats wrong,

**Comment by tommycli** [comment]
I looked at it briefly. I think there's a bug in how I implemented it. Your script looks good.

I will look into what I did wrong when i get a chance.
