### ISSUE TITLE
the npc should check for "touch by player" instead of the player

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#282]
the npc should check for "touch by player" instead of the player

**Comment by tommycli** [comment]
Can you explain this a bit more?

**Comment by hendrik-weiler** [comment]
For example, in rpg maker when you set the event to follow player and say by touch the hero should receive damage, that works.

And here is the touch handled by the hero instead of the event, so it wont fire the event commands.
