### ISSUE TITLE
somewhere picture slot 54-60 upwards it wont be shown

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#289]
somewhere picture slot 54-60 upwards it wont be shown

**Comment by tommycli** [comment]
I tested this by changing the game over picture slot (in menu.js) to 55. Seems to work fine.

**Comment by hendrik-weiler** [comment]
With 60 it doenst work 100%

**Comment by tommycli** [comment]
I tried '60' in the game over code for menu.js, and it worked for me. I changed some code and hopefully that will show a log message if a picture is added that's out of range.

**Comment by hendrik-weiler** [comment]
I think it can be closed
