### ISSUE TITLE
Menu?

### ISSUE THREAD

**Issue by linkigit** [rpgboss/rpgboss#295]
Hi i don't know of it is a bug or that the menu system realy changed but if i press esc if i test
the game a menu won't open and i realy need that or something else to save in one of the other updates it worked well...

**Comment by ravedragon** [comment]
confirmed bug thanks
![export99](https://cloud.githubusercontent.com/assets/8285836/6321152/35d7b53a-baa8-11e4-89e7-3558c56ef260.png)

**Comment by linkigit** [comment]
ok yw

**Comment by tommycli** [comment]
Should be fixed in a4394a913081debb543efedcdf71a96168b0a2c1. Look at next release.

**Comment by linkigit** [comment]
still don't works for me..

**Comment by ravedragon** [comment]
do you have any player stats that are beyond 5 digits?

**Comment by ravedragon** [comment]
also can you screenshot the command prompt, when u play test, and press menu it will show us what the error causing it.

**Comment by linkigit** [comment]
idk what you mean with beyond 5 digits but here is a screenshot
![bandicam 2015-02-24 08-08-50-311](https://cloud.githubusercontent.com/assets/10259891/6344700/8b7f9dd6-bbfc-11e4-8984-b7b9b69954cc.jpg)

**Comment by ravedragon** [comment]
woah that a extremely large stats lol 5 digits = xxxxx/xxxxx hp/mp on a player. right now we should keep it low, until the battle screen get correctly fit it. but if want it higher. we'll consider it. just looks bad on small resolution atm. seeing numbers across the screen.

**Comment by tommycli** [comment]
Your character name is longer than 10 characters. That is the issue. Try a shorter character name.
