### ISSUE TITLE
Character Name in message

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#296]
This is an French Question:
We could have the name of the characters that appear?
With the image?

**Comment by hendrik-weiler** [comment]
Its basically https://github.com/rpgboss/rpgboss/issues/265

But i think aswell having like a textfield where you can write a character name in it, or an checkbox which you check on to display the eventname as first line of the messagebox.

**Comment by tommycli** [comment]
Yep. it's \N[4] etc.
