### ISSUE TITLE
Weapons regarded as items not epuipabble (BUG!!)

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#309]
The Damaged Sword crashed the game every time so I used these and only the Damaged Chestplate was actually equippable. Now the chestplate wont even equip. They are also all set to equipment.
![screenshot 2015-03-08 13 47 34](https://cloud.githubusercontent.com/assets/11379907/6547611/17b07130-c59a-11e4-94cd-21a417334137.png)

**Comment by ravedragon** [comment]
also make sure the character class  can  equiped the item  in the database > classes

**Comment by ravedragon** [comment]
here a screenshot for the missing setup 
![weirdx](https://cloud.githubusercontent.com/assets/8285836/6549295/c136aeb2-c5cd-11e4-8acf-d7edc7272f46.jpg)

**Comment by ravedragon** [comment]
hello has this solve the problem?

**Comment by cartoonzx** [comment]
Sort of. I cant equip like the glove and pant and things  like that.

**Comment by cartoonzx** [comment]
The sword still crashes the game too

**Comment by ravedragon** [comment]
can you screenshot the command prompt. it usually tells us the problem.
