### ISSUE TITLE
Goblin keeps uses turns before i can use mine and doesn't have HP (Question)

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#311]
So when I go int oa battle with an enemy, it has no HP and it uses turns on and on, even if its MY turn. Any way i can fix it? I need to have a stable battle system. 
![screenshot 2015-03-08 17 42 41](https://cloud.githubusercontent.com/assets/11379907/6548595/463fd934-c5bb-11e4-8702-9bb144911524.png)

**Comment by ravedragon** [comment]
it not really a bug, since it a active system (continues atking after cooldown speed is done) the battle system still need alot of work, for now were focusing adding more feature first. unless we have someone who wants to help us improve/develop the custom battle system even further.

**Comment by cartoonzx** [comment]
Ok thanks.
