### ISSUE TITLE
SUGGESTION: add left and right scrolling with setting the tile to teleport to in the teleport menu

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#313]
title says it

**Comment by tommycli** [comment]
Hmm works for me. Can your provide a screenshot where it doesn't work right?

![snapshot22](https://cloud.githubusercontent.com/assets/157358/6702024/fb25c002-cce1-11e4-9eac-f3f71220a9a9.png)

**Comment by cartoonzx** [comment]
Sorry for taking long! ![screenshot 2015-03-17 20 23 06](https://cloud.githubusercontent.com/assets/11379907/6702096/74c27774-cce3-11e4-91f2-7eacae7df06e.png)
