### ISSUE TITLE
SUGGESTION: Add the ability for a night and day system

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#314]
Title says it!

**Comment by hendrik-weiler** [comment]
You can add it by creating a script and using the tintscreen cmd.

For example: 
day state = game.tintScreen(0.788,0.788, 0.778,0.372,0);
night state = game.tintScreen(0,0.105, 0.262,0.376,0);

**Comment by tommycli** [comment]
Not going to built-in. Can be done using tinting as Hendrik described.

**Comment by cartoonzx** [comment]
Could you elaborate on how i could make it using Hendrik's way (what i need to do)?
