### ISSUE TITLE
[BUG] An Window that does not fit the text

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#324]
Hey guys,

I have an bogue with the latest version, i have change the Game text and if you see the screen you can see the bogue

![erreur](https://cloud.githubusercontent.com/assets/923600/6652661/78b1381c-ca76-11e4-8507-c06bec11039d.PNG)

The translation is not fix to the right window

**Comment by cartoonzx** [comment]
This happens with the text boxes aswell.

**Comment by tommycli** [comment]
Hmm.. you could make a copy of menu.js into your project directory and edit the dimensions there.

There's no plans to make the right column auto-size to arbitrary strings...
