### ISSUE TITLE
Can RPGBoss be used for commercial use?

### ISSUE THREAD

**Issue by FyxWolftastic** [rpgboss/rpgboss#329]
I couldn't find anything in the license that says otherwise, but can games made with RPGBoss be sold if you provided a credits.txt file or something that mentions RPGBoss?

**Comment by ravedragon** [comment]
the games you made with rpgboss can be made for commercial, the default asset that comes with rpgboss can be used for commercial also. they are credited in the readme. But every imported asset has their own license that only part you have to look out for.

**Comment by FyxWolftastic** [comment]
Alright. Thanks!
