### ISSUE TITLE
Status Effects

### ISSUE THREAD

**Issue by ravedragon** [rpgboss/rpgboss#33]
well finally testing skills, and some other things, found bugs lol
Status effects , doesnt seem to work as imagine, well it doesnt work.
because i think -10% hp is every tick
but i might assume status effect is not implanted yet .
Also would be nice to add a status effects of sleep
ill probably post, or mail more ideas of skills.

1-3, database, 4-5 Battle test.
![status effects 1](https://cloud.githubusercontent.com/assets/8285836/4100191/937b3c9e-3087-11e4-89aa-f732ba1c01ba.jpg)
![status effects 2](https://cloud.githubusercontent.com/assets/8285836/4100192/9a0b240c-3087-11e4-84f3-a88528f264e7.jpg)
![status effects 3](https://cloud.githubusercontent.com/assets/8285836/4100194/9fbddc14-3087-11e4-8bda-5ec9b0973b2a.jpg)
![status effects 6](https://cloud.githubusercontent.com/assets/8285836/4100214/07b2833c-3089-11e4-8f6d-5bcffd23366e.jpg)
![status effects 5](https://cloud.githubusercontent.com/assets/8285836/4100196/abbc64ea-3087-11e4-90ad-bcb493d887d6.jpg)

![status effects 4](https://cloud.githubusercontent.com/assets/8285836/4100195/a66cfaa4-3087-11e4-9f03-08231d27f4ab.jpg)

**Comment by tommycli** [comment]
Okay some per-tick status effects work now. I'm closing this for now. Make a new issue with specific missing features and bugs.
