### ISSUE TITLE
camera doenst seems to work properly anymore

### ISSUE THREAD

**Issue by hendrik-weiler** [rpgboss/rpgboss#330]
This commit caused https://github.com/rpgboss/rpgboss/commit/1078a24c679ada65b9a56546bd174cbe142d17e0

That the camera doenst move well witht he player anymore
![unbenannt-1](https://cloud.githubusercontent.com/assets/342368/6660959/b79d10e4-cba4-11e4-9f0d-0c8f21608c7e.jpg)

**Comment by ravedragon** [comment]
yes, the default camera doesnt seem to snap to the player.
