### ISSUE TITLE
Option to change controls?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#331]
I see you deleted my other submission, whatever, but what I meant was changing the games controls. Like changing the moving keys, up down left right, to WASD. Is there a way to do that?

**Comment by ravedragon** [comment]
it is being worked on for awhile. eventually will be released shortly.

**Comment by ravedragon** [comment]
and please separate ur question, cause usually when one is complete, we close it since something was done lol

**Comment by hendrik-weiler** [comment]
@tommycli is planning to make it working with a game controller.

So i guess while doing that changeable control keys could be possible.

What @ravedragon means whats being worked on for a while is a feature to capture key input.
A pretty important feature if you want to create your own menus or systems.

**Comment by cartoonzx** [comment]
Thanks for the answers! And I will separate my questions, I just had 10 and didn't think you guys would like 10 different ones haha.
