### ISSUE TITLE
How can I make a person in the players party follow them anywhere they go (even when changing maps) without having to make a whole other event each time?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#341]
How can I make a person in the players party follow them anywhere they go (even when changing maps) without having to make a whole other event each time?

**Comment by ravedragon** [comment]
it not rdy to do that, still being refined

**Comment by cartoonzx** [comment]
Ok thanks

**Comment by hendrik-weiler** [comment]
It should be configurable @tommycli

**Comment by tommycli** [comment]
It would be nice, but probably won't be a core feature before the 1.0 release.
