### ISSUE TITLE
Glitch?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#343]
![screenshot 2015-03-31 21 22 54](https://cloud.githubusercontent.com/assets/11379907/6934603/278f2dc6-d7ec-11e4-8321-a28b95bf7fae.png)
Not sure why the names and prices are like this?!

**Comment by tommycli** [comment]
The "Xs" denote when the length of the name or number has exceeded the space allocated.

**Comment by cartoonzx** [comment]
Thanks. This seems unappealing though.

**Comment by ravedragon** [comment]
try reduce your font size or increase your resolution >database>setup

**Comment by hendrik-weiler** [comment]
how to reduce the font size?

**Comment by ravedragon** [comment]
this lol
![export109](https://cloud.githubusercontent.com/assets/8285836/6959262/b0014ec0-d8cb-11e4-9058-c0f2cf669ab7.jpg)

**Comment by cartoonzx** [comment]
Eyy Thx
