### ISSUE TITLE
Better looking UI in battle?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#345]
I've seen some gameplay of RPG Maker battles and it seems to run real smooth and has smooth transitions, and all that, and I think it should be kept in mind that Rpgboss should have a nice smooth battle UI just like RPG Maker does. Also being able to select which person in your party goes rther than being linear. Just a thought :)

**Comment by ravedragon** [comment]
we shouldnt mention rpg.-.--.-.maker, they'll think we trying to copy them lol, anyways, right now were adding core feature before 1.0.0 coming out with improvements and remodeling ui. unless we have more developers willing to work on those request

**Comment by hendrik-weiler** [comment]
cartoonzx since you contribute a lot lately.

Do you have any experience with scala/java/javascript?

**Comment by cartoonzx** [comment]
I have never learned javascript but I would love to learn to help out Rpgboss because I love the project.

**Comment by hendrik-weiler** [comment]
Heres a free course:
http://www.codecademy.com/tracks/javascript

With this tutorial you learn the basics of javascript.
If you have finished you should be able to grasp better how to use it for rpgboss.

With javascript you would be able to do stuff like creating own menus, health bars, manipulating events and stuff.

**Comment by cartoonzx** [comment]
Thank you, I will look into it.

**Comment by cartoonzx** [comment]
Maybe take Final Fantasy into consideration, if you will re model when the 1.0 build releases :)
