### ISSUE TITLE
Event will not activate after changing state with this script

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#346]
![screenshot 2015-04-02 00 43 28](https://cloud.githubusercontent.com/assets/11379907/6959796/52c6fa4c-d8d1-11e4-8f25-8947ea9a55db.png)
This event will not be triggered by pressing space on it after it changes it's state to 1. How can I fix this?

**Comment by ravedragon** [comment]
what does state 0 says

**Comment by ravedragon** [comment]
btw both are triggered, for the 2nd one, use <= less than signs

**Comment by ravedragon** [comment]
also have else checked

**Comment by cartoonzx** [comment]
![screenshot 2015-04-02 00 49 15](https://cloud.githubusercontent.com/assets/11379907/6959875/0f480878-d8d2-11e4-886e-b979bd35ce8b.png)

**Comment by cartoonzx** [comment]
How would i use a < sign on the second one

**Comment by ravedragon** [comment]
actually for more simple just do if + else
because if player has enough items, it will trigger first option, if it doesnt met the requirement it will trigger the next option in *
![export110](https://cloud.githubusercontent.com/assets/8285836/6959924/a363437e-d8d2-11e4-938a-314ede215b1f.jpg)
else*

**Comment by cartoonzx** [comment]
Ahh. Thanks a lot!
