### ISSUE TITLE
Characters on map

### ISSUE THREAD

**Issue by Mannyzilla** [rpgboss/rpgboss#354]
Hello again I was wondering if you can put characters on the map and if so then please tell me how and if you can't then please add that. Thank you.

**Comment by Wend1go** [comment]
Assuming you mean characters = NPCs (and not letters):
These are regular events that you can add by right click on the map -> add event.
Click on the white area underneath "Sprite:" and select the image of a character.

**Comment by Mannyzilla** [comment]
Thank you!!!!
