### ISSUE TITLE
BUG: Windows XP - Game won't test/animations window glitchy

### ISSUE THREAD

**Issue by Scotty2Hotty999** [rpgboss/rpgboss#357]
The editor works perfectly fine in Windows XP, but when I try to test a game, it takes like 5 seconds and the editor becomes unresponsive (like the game is running) and then it goes back to the editor again, (like the game opens and then crashes in a matter of seconds.)

Also, when I view an animation in the animations window in the database, this shows up.

![untitled](https://cloud.githubusercontent.com/assets/10061401/7158462/5fb393ec-e348-11e4-8f66-6435acbce2c5.JPG)

Thanks!

**Comment by Wend1go** [comment]
Could you run the editor from the command line and post it's output when the error happens?

**Comment by ravedragon** [comment]
if you test the game, and does not show but u can hear the game is running, that means one of the event, has a error, iike a change of resource that was deleted, or a missing event state. etc. screenshot the command prompt it usually tell us what causing it.

**Comment by Scotty2Hotty999** [comment]
This is what I got....

![](http://i.snag.gy/z0ZLC.jpg)

**Comment by tommycli** [comment]
The error message says it all: You need OpenGL 2.0 or higher with the FBO extension. No plans to support XP, it's already been end-of-lifed by Microsoft.
