### ISSUE TITLE
Events are not able to activate after 0.8 Update

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#363]
For some reason they no longer work...

**Comment by ravedragon** [comment]
it is confirmed in 0.8.2 try 0.8.3

**Comment by cartoonzx** [comment]
Where can I download it?

**Comment by ravedragon** [comment]
oh i see, cant edit or make new ones.

**Comment by cartoonzx** [comment]
No, I cannot activate them at all.

**Comment by ravedragon** [comment]
are they with custom sprite?

**Comment by ravedragon** [comment]
can u screenshot ur command prompt

**Comment by cartoonzx** [comment]
It got fixed with 0.8.3

**Comment by ravedragon** [comment]
ok

**Comment by cartoonzx** [comment]
Thank you though!!!
