### ISSUE TITLE
Can you export OSX games on Windows?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#369]
I don't see any OSX files when I export on Windows. IS it possible to export OSX on Windows?

**Comment by ravedragon** [comment]
ppl will be able to play in osx using the linux version export.

**Comment by ravedragon** [comment]
but still looking to make a separate files for osx, but for now people use the same files as the linux.zip

**Comment by cartoonzx** [comment]
Ok thanks!
