### ISSUE TITLE
Call Menu and Call Save Menu events don't work

### ISSUE THREAD

**Issue by NothingForgotten** [rpgboss/rpgboss#370]
If you try to use one of these two Event Commands the menus wont show up inside the game. I was able to fix the bug for the Save Menu by my self by editing line 96 of the file /defaultrc/script/sys/globals.js inside the .jar-file. I changed it to: 'game.runScript("sys/menu.js", "SaveMenu()");'.
I tried to fix the Call Menu event on the same way (changed line 100 to : 'game.runScript("sys/menu.js", "Menu(details)");') but it still dosn't work. It seems like there is no entity of the details-class (that seem to be used by the Menu-function) is defined.

**Comment by hendrik-weiler** [comment]
I dont know whats causing it, but you can fork the repo and try to fix in
https://github.com/rpgboss/rpgboss/blob/master/common/src/main/resources/defaultrc/script/sys/menu.js

You can then create a pull request and then it gets decided if this fix is ready to be merged into the main repository.

**Comment by tommycli** [comment]
Thanks for the fixes!
