### ISSUE TITLE
Add quests!

### ISSUE THREAD

**Issue by Shrovack** [rpgboss/rpgboss#374]
Add a quest menu, or something to make it easier to make/manage quests. also ADD quests! what is an RPG without Quests?!

**Comment by cartoonzx** [comment]
PLEASE!

**Comment by HenrikoMagnifico** [comment]
This would be so totally awesome. Great idea!

**Comment by TheArle** [comment]
You already can, just use global variables and event trigger conditions. It's not too hard.

**Comment by tommycli** [comment]
Exactly what TheArle said.
