### ISSUE TITLE
make pictures like a text box!

### ISSUE THREAD

**Issue by Shrovack** [rpgboss/rpgboss#377]
I tried to m=incorporate a picture into my game but when you activate the event it only shows it for a split second! you should make it so that you have to press a button to continue like the text boxes are.

**Comment by ravedragon** [comment]
add sleep after the picture  than can remove

**Comment by Shrovack** [comment]
Is that a solution to my problem or just adding on to my enhancement?

**Comment by ravedragon** [comment]
yes.

**Comment by tommycli** [comment]
Make three events:

1. Show Picture
2. Get Key Input (wait for an OK key)
3. Hide Picture

That should do what you want.
