### ISSUE TITLE
Sprite Sheet selection only uses a fraction of the actual sprite?

### ISSUE THREAD

**Issue by cartoonzx** [rpgboss/rpgboss#380]
So this happens. And this IS 384x256. Could you help me out? Also, the tool I am using is at http://www.mmorpgmakerxb.com . Thank you.
![screenshot 2015-05-20 21 38 19](https://cloud.githubusercontent.com/assets/11379907/7741774/09e0b1a4-ff39-11e4-9ecb-8b4e74a9c261.png)

**Comment by ravedragon** [comment]
i do not know what the sprite sheet size renders at but i suggest you try to get it in 3x4
for 256x384 i see the editor trying to turn everything into 64x64

**Comment by cartoonzx** [comment]
So what resolution I set the sprite sheet to?

**Comment by cartoonzx** [comment]
And what do you mean by 3x4?

**Comment by ravedragon** [comment]
my bad it 1x2 example 96x192 etc

**Comment by cartoonzx** [comment]
96x192 made it 3 panel, but only selected a fraction of the sprite.

**Comment by ravedragon** [comment]
ah i see what tommy did, the minium size are set to 384x384, the 92x196 u might have to use the same png in the default folder, and copy paste over it, will have to post a bugfix/enchancement to let imported smaller size in

**Comment by cartoonzx** [comment]
I need help with this, I really need to use this sprite. I don't know why it doesn't work. I have other sprite sheets that are 256x384 and they work fine.

**Comment by tommycli** [comment]
Attach a copy of the sprite file.

**Comment by cartoonzx** [comment]
What resolution do you want?

**Comment by cartoonzx** [comment]
![spritexb-6803](https://cloud.githubusercontent.com/assets/11379907/7781903/26b77776-00b1-11e5-9780-81d4b43c4b76.png)

**Comment by cartoonzx** [comment]
So...

**Comment by cartoonzx** [comment]
So?

**Comment by cartoonzx** [comment]
... Have you fixed it the issue...

**Comment by tommycli** [comment]
Spritesheets need to follow this format: https://github.com/rpgboss/rpgboss/blob/master/common/src/main/resources/defaultrc/spriteset/sys/vx_chara01_a.png

Unless they have a '$' at the front of the filename, in which case a single sprite is on an image:
https://github.com/rpgboss/rpgboss/blob/master/common/src/main/resources/defaultrc/spriteset/sys/%24vx_chara09_a.png

It seems that the tool generates sprites with one extra animation frame, so it will probably require using an image editing tool to make it comply with the rpgboss formats.

**Comment by blurymind** [comment]
only three frames per cycle. Seems like a massive limitation

**Comment by cartoonzx** [comment]
Could you send me the sprite file I sent but fixed so it works?
