### ISSUE TITLE
Is there any "normal" wall ?

### ISSUE THREAD

**Issue by Herrgaeon** [rpgboss/rpgboss#381]
while I was trying to make the outside of a house, I couldn't find a brick wall which wasn't covered by the shadow of the roof. So I'd like to know if It's only me who have vision trouble, or if there no "normal" wall ?
Thank you.

**Comment by ravedragon** [comment]
any screenshot to see what u mean?

**Comment by Herrgaeon** [comment]
![screenshot from 2015-05-31 11 16 56](https://cloud.githubusercontent.com/assets/12674454/7901435/9aa47720-0786-11e5-91c3-02d77edd0ff9.png)

**Comment by Herrgaeon** [comment]
There are those black spot on it, and I couldn't find a wall without them.

**Comment by ravedragon** [comment]
those tiles are related to the red and blue rooftops in T0

**Comment by tommycli** [comment]
The normal walls are in the "A" tab. Just look for the similar texture and start making rectangles with it. It's an autotile, so it will make the wall borders automatically.

**Comment by Herrgaeon** [comment]
Ok thanks a lot to all of us for your help !
