### ISSUE TITLE
Transparency?

### ISSUE THREAD

**Issue by markthebirdy** [rpgboss/rpgboss#382]
I'm currently creating a game and in it, I have created the first cutscene in which the main hero is not involved. The only way I can figure out how to do this is to set the character's spirite to "none" and the scene plays out just fine. However when I tell an event to teleport the player to the next map/scene, he is still set to nothing. If I try to set the start location in the second map with the character sprite selected, the game starts there instead of the first scene. Is there a way to have the game start with the first cutscene without the character being there or can I have the character transparency for the first cutscene then have him visible in the next? So confused and frustrated. PLEASE HELP! Lol

**Comment by ravedragon** [comment]
i think after moving the camera just teleport the player, after the camera ends. dont need to move the starting point.

**Comment by ravedragon** [comment]
and for ur starting point. i think u should use autorun for first time cut scene?
