### ISSUE TITLE
An option to encrypte data

### ISSUE THREAD

**Issue by Caranille** [rpgboss/rpgboss#383]
Hi guys,

I have an good idea, why you don't create an option to export our game with data encrypted.

Exemple: I want to publish my game but I do not want the players to modify it to make it their own

**Comment by Shrovack** [comment]
if you are on windows go into the games export file and click on the things you don't want people to be able to use, go into properties and hide them. zip the file and people shouldn't be able to use the editor

**Comment by tommycli** [comment]
Any obfuscation of the data would be pretty superficial.
