### ISSUE TITLE
Text box displays each word on its own seperate line

### ISSUE THREAD

**Issue by TheArle** [rpgboss/rpgboss#385]
I entered text into a text box function. However, when I loaded it, it came out like this.
![screenshot 2015-06-10 12 42 29](https://cloud.githubusercontent.com/assets/8650610/8088289/2fefb92c-0f6e-11e5-9149-4feec34456a6.png)
Is there any way to fix this?

**Comment by hendrik-weiler** [comment]
You should copy and paste the text in this issue and explain better whats the problem is.

**Comment by cartoonzx** [comment]
I didn't even know you could change that. Where do you get your skins?

**Comment by cartoonzx** [comment]
Oh yeah, this bug happened to me as well, and I am on Windows. ![screenshot 2015-06-11 15 00 32](https://cloud.githubusercontent.com/assets/11379907/8119486/a742af16-104a-11e5-941e-6ef3d3d4ed89.png)
