### ISSUE TITLE
NPC walking edits

### ISSUE THREAD

**Issue by marbuljon** [rpgboss/rpgboss#392]
I think it would be good if we could edit the walk speed or area when NPCs are set to being able to walk around. Something simple like "slow, medium, fast" and "move all over the map" or "be able to move 30 tiles away from start point". I set an NPC to walk randomly but it seems to move really fast and wanders down to where i haven't placed anything on the map, so I thought it was a bit funny. If there's already a way to do this, sorry for submitting this.

**Comment by ravedragon** [comment]
you can use set event speed for now, we only have basic function until more stuff are added

**Comment by marbuljon** [comment]
Okay, thanks!
