### ISSUE TITLE
Deleting tiles bug!

### ISSUE THREAD

**Issue by marbuljon** [rpgboss/rpgboss#395]
Hey, my friend deleted a tile that was in use on their map, and it broke the program. Now it can't open because it's looking for tiles that don't exist anymore. So the program needs a "if can't find tile, change that tile to a default tile" safety feature.

**Comment by ravedragon** [comment]
what kind of delete do you mean? 
Deleting the png files? tiles replaced? or have a screenshot ? lol

**Comment by marbuljon** [comment]
They had imported a single tile instead of a tileset, so they tested it in the game and then clicked "delete" inside the "resources: import" window. They didn't delete the actual png files or do anything else, it seems.

**Comment by ravedragon** [comment]
ah imported tiles, i suggest re-import the same tiles, and than replace it.

**Comment by marbuljon** [comment]
It's okay, it seems that with their reply above that they figured out how to fix it, but they're saying that "I would guess that the program didn't really delete all the files and that was the problem, so that should be looked into".

**Comment by hendrik-weiler** [comment]
@tommycli maybe create a dialog which lets you replace broken references?
