### ISSUE TITLE
*IMPORTANT* Mac problem.

### ISSUE THREAD

**Issue by Dannnnnnnn** [rpgboss/rpgboss#397]
My mac crashed when I was using this program. When I opened it after relogging, the editor window didn't come up, nor did the "Select a Project" window. Please find a way in which I can open either window once again.

**Comment by ravedragon** [comment]
have you try the older version?

**Comment by hendrik-weiler** [comment]
We will look into it.

**Comment by hendrik-weiler** [comment]
Well i tried to run the editor and seems to work. It seems the connection was always on. So i have no clue about your problem.

**Comment by Dannnnnnnn** [comment]
I might as well take pics and show you what the problem is, the type of Mac I'm using, and how I got the problem.
(If images don't show up, I'll repost another comment with them)
/2015-07-07 02.26.13 pm.png
/2015-07-07 02.27.10 pm.png
/2015-07-07 02.27.52 pm.png
/Screen shot 2015-07-07 at 2.37.29 PM.png

**Comment by Dannnnnnnn** [comment]
... Guess the image upload doesn't work here. Might as well send it by email.

**Comment by Dannnnnnnn** [comment]
Here's the problem (Yet I'll show you what I'm using and what I did, and check them in the order I gave you)

**Comment by Dannnnnnnn** [comment]
Argh, how did this end up here? Oh well, Might as well try again.

**Comment by Dannnnnnnn** [comment]
Nevermind about this. Already solved on my own.
