### ISSUE TITLE
Ok button not showing

### ISSUE THREAD

**Issue by TheHiddenGhost** [rpgboss/rpgboss#399]
When I create a new event there isn't an ok or cancel button at the bottom of the GUI. Can someone please help?

**Comment by tommycli** [comment]
Maybe your monitor is just extra short? Can you take a screenshot?

**Comment by TheHiddenGhost** [comment]
![screen shot 2015-07-15 at 10 33 48 am](https://cloud.githubusercontent.com/assets/13343358/8700965/0bae200a-2add-11e5-9524-ab93d0581a1a.png)

Under the No Errors. part of the GUI, there is nothing. It just gets cut off there.

**Comment by TheHiddenGhost** [comment]
I'm also on a Macbook Air btw

**Comment by TheHiddenGhost** [comment]
Nvm all i had to do was minimize my dock and enlarge the gui!
