### ISSUE TITLE
Whenever the game shows a message from an npc, the entire game freezes and I have to force quit it

### ISSUE THREAD

**Issue by weesine** [rpgboss/rpgboss#402]
I am just starting out and I wanted to have an npc talk at the beginning of my game but whenever it tries to show an in game message, it freezes the entire game.

**Comment by ravedragon** [comment]
can u screenshot the event.

**Comment by Hamyuiop** [comment]
The latest release fixed the issue for me, so if you haven't already, get the latest version.

**Comment by weesine** [comment]
Thanks i'll check in a bit.

**Comment by weesine** [comment]
Okay
It works but after It shows text it repeats the text. Am I just not doing something right or is it a legitimate problem?

**Comment by ravedragon** [comment]
i assume u want it to change state to the next one?, there should be a command to change state #

**Comment by weesine** [comment]
Oh.
Thanks a bunch!
