### ISSUE TITLE
Using Ogg Audio instead Mp3 Audio for the standardrc?

### ISSUE THREAD

**Issue by NothingForgotten** [rpgboss/rpgboss#405]
I noticed that RPGBoss uses a lot of audio files in the mp3 format, wich is closed source.

I think for a open source project like this it would be better to use free codecs like ogg-Vorbis. Especially because it has Linux support.
The most Linux users won't have a problem with mp3-audio but for example in the USA or Japan(as far as I know) there are laws to prevent them from simply install a mp3 codec on their system. Besides there are also a few people around who simply want to avoid close source formats.
RPGBoss should not suspend them from making own games with it.

**Comment by ravedragon** [comment]
hmmm

**Comment by tommycli** [comment]
Seems reasonable. If you want to convert all the MP3s to OGG and can maintain a similar filesize and quality, then update enumerated.txt, I would be happy to accept a pull rquest.

**Comment by tommycli** [comment]
Thanks for the pull request!
