### ISSUE TITLE
Personal problem solved, minor issue incoming.

### ISSUE THREAD

**Issue by Dannnnnnnn** [rpgboss/rpgboss#406]
Finally got the program to work again, but there's a minor issue... My titles that I imported aren't showing up. Do I have to perform a certain action in order to import my titles, or do I have to change the overall size of my titles (And in case you need the sizes, one of them is 512x480, two are 512x512, and the last one is 256x384.)?

**Comment by ravedragon** [comment]
i think you created a project within a project?

**Comment by Dannnnnnnn** [comment]
A project within a project... how does that work?

**Comment by ravedragon** [comment]
oh u meant tiles.

**Comment by Dannnnnnnn** [comment]
*Sighs* Yes. I meant titles.

**Comment by ravedragon** [comment]
right click on the map get a drop menu > map properties > add.. > select ur imported tiles

**Comment by ravedragon** [comment]
![export123](https://cloud.githubusercontent.com/assets/8285836/9020535/77efe66c-37c7-11e5-9f63-fe2b5952b314.jpg)

**Comment by Dannnnnnnn** [comment]
Thanks mate. :D
