### ISSUE TITLE
Menu Crashing on 0.9.3

### ISSUE THREAD

**Issue by Dannnnnnnn** [rpgboss/rpgboss#407]
When I tried to open my menu, even when I tried to talk to an NPC, the game crashes for no reason. I don't know if it has to do with the icons or the new updated program, but someone has to shout out on why this is happening.

**Comment by ravedragon** [comment]
thnx this is a bug with the current version

**Comment by ravedragon** [comment]
i suggest using 0.9.2 for now

**Comment by ravedragon** [comment]
![export122](https://cloud.githubusercontent.com/assets/8285836/8924278/9439a6ce-34b0-11e5-9e50-eb209a92bd35.jpg)

**Comment by Dannnnnnnn** [comment]
Ah, ok. Thx.

**Comment by ravedragon** [comment]
open till fix
