### ISSUE TITLE
Battle is broken

### ISSUE THREAD

**Issue by markthebirdy** [rpgboss/rpgboss#410]
When I try to test battles, 90% of the time it crashes with the music still playing but the during the 10% of the time there is still a problem: the enemies don't lose any health from attacks. I am so confused.

**Comment by tommycli** [comment]
Can you post the error message?

Also, can you try using the new default skills from here?
https://github.com/rpgboss/rpgboss/tree/master/common/src/main/resources/defaultrc

Copy skills.json and classes.json into your project directory. Back up your originals.

**Comment by markthebirdy** [comment]
Here is the error. Now there is a possibility that the crashes are happening due to my PC being a very sucky one but still 
![error](https://cloud.githubusercontent.com/assets/12737797/9706540/a8d35fc6-54a4-11e5-9377-64ebc214b86d.jpg)

**Comment by markthebirdy** [comment]
I'm still not used to this so how do I download the json files?

**Comment by tommycli** [comment]
Zip up the whole project directory and email to rpgboss@keepword.com

Thanks.

**Comment by ravedragon** [comment]
i remember you say you changed the damage , u should remember to use a.atk or a.mag
