### ISSUE TITLE
Clarify GPL version.

### ISSUE THREAD

**Issue by Jookia** [rpgboss/rpgboss#411]
The source code shows no license information such as which version of the AGPL it's released under, or whether it allows upgrading to a newer version. This clarification is needed.

**Comment by tommycli** [comment]
See https://github.com/rpgboss/rpgboss/blob/master/LICENSE.txt. It says the version in there.

**Comment by Jookia** [comment]
That license says I can use whichever GPL version I want.

**Comment by tommycli** [comment]
It's this one: http://www.gnu.org/licenses/agpl-3.0.en.html

**Comment by tommycli** [comment]
Line 9 of LICENSE.txt file contains the version.

**Comment by Jookia** [comment]
Line 580 specifies that if the copyrighted work doesn't specify which version of the AGPL3 it's licensed under, any AGPL version can be chosen. For instance, https://github.com/rpgboss/rpgboss/blob/master/editor/src/main/scala/rpgboss/editor/MainPanel.scala doesn't specify the version.
