### ISSUE TITLE
the game package cannot download dirrectly into the editor.PLEASEEE! HELP ME!

### ISSUE THREAD

**Issue by muhammadadenfauzan** [rpgboss/rpgboss#418]

**Comment by ravedragon** [comment]
which?

**Comment by muhammadadenfauzan** [comment]
legend of black stone
download link:https://drive.google.com/file/d/0B5it6hamiiBsUmJMa3RFeU5mUnc/view?usp=sharing
can you please tell the admin

**Comment by hendrik-weiler** [comment]
I believe it was never meant to be possible to download a whole project directly into the editor.
