### ISSUE TITLE
How to change NPCs velocity? The NPCs are crazy on the map.

### ISSUE THREAD

**Issue by GoroDaimon** [rpgboss/rpgboss#422]
Where can I choose the NPCs speed?

**Comment by ravedragon** [comment]
npc speed? i assume the walking movement?, that the command call set event speed

**Comment by GoroDaimon** [comment]
Thanks!

**Comment by tommycli** [comment]
Use "Set Event Speed" event command to change speed.

There's no route support. But you can use "Move Event" command.

**Comment by tommycli** [comment]
Oh I understand, the Random movement is crazy.

**Comment by tommycli** [comment]
Duplicate of #424
