### ISSUE TITLE
No 320x240 Windowed screen!

### ISSUE THREAD

**Issue by GoroDaimon** [rpgboss/rpgboss#423]
Why I CAN'T set screen to 320x240? I Need to scale by mouse click to fit in 320x240 on Gnu/Linux.

**Comment by ravedragon** [comment]
i dont think the dev has set the screen that small ,

**Comment by muhammadadenfauzan** [comment]
What game you are making?Do you already upload it?

**Comment by GoroDaimon** [comment]
ravedragon. 320x240 only for windowed mode please. Fullscreen must 640x480.

**Comment by tommycli** [comment]
You can resize the window to be smaller than 640x480 after starting it.

But the 'system resolution' cannot go below 640x480.
