### ISSUE TITLE
I finnally know where the tileset,char and faces are from! Am I right? 

### ISSUE THREAD

**Issue by muhammadadenfauzan** [rpgboss/rpgboss#433]
http://rpgmaker.net/media/content/users/21676/locker/FSM_REFMAP.zip

But can you tell me where is the other resource is from:
Music,Battle animation,Enemy graphics,etc. 
please,i want to know more

**Comment by finkiki** [comment]
Why you want to know what ? You could use any tileset you want.

**Comment by muhammadadenfauzan** [comment]
I am affraid is not for commerscial use

**Comment by muhammadadenfauzan** [comment]
Your chat time for me is on 12pm
WIB (waktu indonesia barat/west indonesia time).where do you live? how old are you
I am15 years old

**Comment by finkiki** [comment]
France

**Comment by ravedragon** [comment]
the original source is from a japanese website that hasnt been renewed for a long time, but yes they are free to use, as long you credit them http://www.tekepon.net  http://www.tekepon.net/fsm/modules/refmap/index.php?mode=rules you have to use internet archive to search past working history lol

**Comment by muhammadadenfauzan** [comment]
the website is already gone

**Comment by tommycli** [comment]
The credits for all the resources are in the README. There's no problem with commercial use as long as you give credit. As far as i know.
