### ISSUE TITLE
Won't let me play

### ISSUE THREAD

**Issue by TheRuneFactoryGuy** [rpgboss/rpgboss#436]
I was able to play yesterday but today after I started working on my project some more it just wouldn't let me test my game. This is the first time it has happened to me and I did restart my laptop even and it still won't work. I am on mac by the way, if this will help. I just hope someone can help me out.

**Comment by ravedragon** [comment]
what was the recently changes you made

**Comment by TheRuneFactoryGuy** [comment]
First I added a few tile sets into it - Didn't give any problems
Added a custom title image - Didn't give any problems
Saved and closed out of it
Opened it up next day and it wasn't working.
I even tried to put it in a new project and it didn't work.
Next I went and did a new project and did everything that i did before and it was fine. I think it just could of been a hiccup in the program but no clue. At this point i don't really care about getting that project back but I just am vary curious on what happened.

**Comment by ravedragon** [comment]
I suggest a screen shot of the command prompt usually show all error

**Comment by TheRuneFactoryGuy** [comment]
I can't get a screenshot of the problem therefor I got a recording of what happened. But I can't post a raw video clip therefor I have it zipped. Hopefully you can download it and view it.
[Problem with RPGBOSS.zip](https://github.com/rpgboss/rpgboss/files/59414/Problem.with.RPGBOSS.zip)

**Comment by tommycli** [comment]
Probably a breaking change between versions.

If you have an error log from the command prompt, please post. Thanks!
