### ISSUE TITLE
Problem to sign up at rpgmaker.net

### ISSUE THREAD

**Issue by muhammadadenfauzan** [rpgboss/rpgboss#440]
I typed no in the 
are you a robot? 
just type"no here"
but i still cant register
it says "no robots allowed"
maybe i will sumbit my game in the next update.

**Comment by ravedragon** [comment]
This should be in "Choice Event"
for example
Case0 = yes
Add text (no robot allowed) event by double clicking >>> in the choice event 
Case1 = no
Add text ( something here ) event
Add set event state to 1
default = if player press ESC
