### ISSUE TITLE
How to disable a Message after it's read once ?

### ISSUE THREAD

**Issue by Tchey** [rpgboss/rpgboss#442]
Hello,

As the forum seems empty and i'm waiting for account confirmation, i hope it's fine to post here.

I want to set some Event to open a Message box, when the player walk somewhere, to describes things, give some background, etc.

But whenever the player enters such an Event, the Message keeps opening until the player manage to get out of the tile, pixel after pixel...

How to do that ?

Same when the player opens a chest, Message is the same all the time. How to make a new message after the chest is looted ?

Thanks

**Comment by ravedragon** [comment]
Add a new state and in the first state add a command to change state after the text is done

**Comment by Tchey** [comment]
Thanks !
