### ISSUE TITLE
I can't use imported tilesets

### ISSUE THREAD

**Issue by Tchey** [rpgboss/rpgboss#443]
Hello,

When i try to import tilesets, i can see them in Ressources/Tilesets, and i can see if they are passable etc, but i can't see them anywhere in the main UI. Are they supposed to be in a new tab, like A, T0, T1, T2, T3 and T4 ?

I tried with maybe 10 of them, from http://assets.rpgboss.com/ and from other open sources. Do import, i go to Import, i click on Tileset, then Import, then i select my .png then i can see it in the list with others, like : sys/Refmap-TileA5.png (built-in)

And that's it. I don't know where to find them in UI to use them on my map.

**Comment by ravedragon** [comment]
Right click on the map menu and import

**Comment by Tchey** [comment]
Thanks !

Some sets don't fit the tabs, and i can't access them all, because it's too large. I can't seem to resize the left panel, can i ?
