### ISSUE TITLE
I make a PDF tutorial, check it out!

### ISSUE THREAD

**Issue by muhammadadenfauzan** [rpgboss/rpgboss#445]
I make this tutorial with :
1.Images (to make this tuorial not boring)
2.big fonts (Easier and quicker to read)
3.write using Arial Black font
4.colored text (easy to noticed)
5.detail instrution

download at
https://drive.google.com/file/d/0B5it6hamiiBsVmtQdkJZSXlPeDA/view?usp=sharing

is there anything I should fix?
please comment.

**Comment by kirbyfan64** [comment]
The font is a tad bit...blinding...

**Comment by muhammadadenfauzan** [comment]
I change the font into arial black

**Comment by tommycli** [comment]
Please consolidate the tutorial contents with the documentation in the Wiki: https://github.com/rpgboss/rpgboss/wiki
