### ISSUE TITLE
Problem with imported sprite sheet

### ISSUE THREAD

**Issue by saltyturnip** [rpgboss/rpgboss#448]
When I went to select which sprite to use for a character, for some reason the program will not let me select the full sprite that I want to use (ex. it will only let me choose part of the head). Is this a problem with sizing? I am fairly sure that everything is sized as it should be.

**Comment by muhammadadenfauzan** [comment]
the sprite sheet should be 384x384 pixels
![vx_chara04_b](https://cloud.githubusercontent.com/assets/12779430/12083829/c3ad5b30-b2dc-11e5-9a4c-870a187b1818.png)
like the built in charset

**Comment by muhammadadenfauzan** [comment]
with 48 height and 32 width
