### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by DiamondMob04** [rpgboss/rpgboss#462]
How do I use the choice button when I use events? I can add the choices, but then how do I make it so when the player chooses a specific choice, something happens that is different from the other???

**Comment by gregorymjason** [comment]
Right, it's almost like I need to be able to create some code for the different cases that are generated from choice, but I can't figure out how to get into that code either.

**Comment by gregorymjason** [comment]
Ok so I figured this out... You are going to want to click on the >>> after the case within the commands part of the event. I have attached a screenshot.
![screen shot 2017-01-16 at 7 31 09 pm](https://cloud.githubusercontent.com/assets/20270436/22005653/61555fd0-dc22-11e6-82e5-ed3daa6d3e71.png)

**Comment by DiamondMob04** [comment]
This thread is really old, I've stopped using RPGMaker, but thanks anyways! I might use it again in the future! I'm going to close this thread now.
