### ISSUE TITLE
crafting option

### ISSUE THREAD

**Issue by ravedragon** [rpgboss/rpgboss#51]
I know people can create their own script of crafting items/ fusing character etc.
i think it might be good if i add a basic conceptual idea for crafting/fusion etc.

**Comment by HumanG33k** [comment]
i have create a abstract function for farming but it need a sprite option selection if it's possible.

if (game.countItems(toolNeeded) >= 1){
  game.addRemoveItem(itemFarm, 3);
  game.showText["Receveid " + getItemName(itemFarm) + " ( x3)."]);
}else{
  game.showText(["You need + getItemName(toolNeeded) + "."]);
}

But it look doesn't work in this state. Can no choice items when i create a new instance.
If somebody have some ideas i take it.

**Comment by tommycli** [comment]
I can add an instance parameter. Which field do you need parameterized?

**Comment by HumanG33k** [comment]
for the sprite, for maybe a list of tools, and a list of farm items with their number or ramdom range. 
For each "tool" if will be destroy after use or the number of charge of the tool. 
Something like that could be cool .
this is just some ideas for a modular functionnalitie for farm and profession.
