### ISSUE TITLE
Solved - How to encrypt the game

### ISSUE THREAD

**Issue by kholyphoenix1** [rpgboss/rpgboss#521]
Hello, 

How I can encrypt my game when finish Project?
RPGBoss has this support in protect project?

Thanks a lot!

**Comment by AntumDeluge** [comment]
I honestly don't know for sure, but I doubt that it has that capability.

**Comment by kholyphoenix1** [comment]
It would be interesting to include the game's encryption when finished to publish.

**Comment by EgyLynx** [comment]
I doubt that will finished someday :( .

**Comment by ghost** [comment]
What you are wanting(to publish encrypted media) is DRM, and DRM requires proprietary software. This is an open source project. DRM is also normally done through a game manager like Steam, not the game engines. 
Please close this issue.
