### ISSUE TITLE
Size/Dimensions of a Sprite Set/Sheet?

### ISSUE THREAD

**Issue by mattymoo666** [rpgboss/rpgboss#529]
I've made my own sprite set but it clearly isn't the right size, as when I put it into RPGBoss and try to select a sprite, it will only select part of it and not the whole sprite.

When making a sprite set, what size should to whole set be (in pixels), and what size should each individual sprite be within the set (in pixels)?

I've been looking online for the correct dimensions and couldn't find anything.

**Comment by AntumDeluge** [comment]
So, there may be a couple of issues here.

1. How many spritesets are in your sheet? By default, RPGBoss assumes spritesheets to to have 8 spritesets in two rows:

    [vx_chara01_a.png](https://github.com/rpgboss/rpgboss/blob/894ba5f/core/src/main/resources/defaultrc/spriteset/sys/vx_chara01_a.png)
    ![Preview default](https://raw.githubusercontent.com/rpgboss/rpgboss/894ba5f7d128b95a1633d5a55859e68c56625abf/core/src/main/resources/defaultrc/spriteset/sys/vx_chara01_a.png)

    If you want to override this for just a single sprite, you need to prefix the image's filename with a dollar symbol ($):

    [$vx_chara09_a.png](https://github.com/rpgboss/rpgboss/blob/894ba5f/core/src/main/resources/defaultrc/spriteset/sys/%24vx_chara09_a.png)
    ![Preview single](https://raw.githubusercontent.com/rpgboss/rpgboss/894ba5f7d128b95a1633d5a55859e68c56625abf/core/src/main/resources/defaultrc/spriteset/sys/%24vx_chara09_a.png)

2. As far as sprite dimensions go, I don't think that RPGBoss discriminates. As long as there are the correct number of sprites & frames in the image, it will automatically determine size. However, RPGBoss currently only supports 32x32 tilesets (as far as my understanding goes). So, sprites around 32x32 or 32x48 tend look best.

**Comment by mattymoo666** [comment]
Thanks so much! That cleared it up for me😊

**Comment by ghost** [comment]
Please close the issue.

**Comment by EgyLynx** [comment]
Hmm, At one think isn´t Rpg makers use that same?

**Comment by AntumDeluge** [comment]
The sprites that come built-in to RPGBoss were actually made for RPG Maker.
