### ISSUE TITLE
[Feature Request] Adjustable Title Menu Position

### ISSUE THREAD

**Issue by ghost** [rpgboss/rpgboss#530]
As far as I can tell there is no way to change the position of the title window(menu). This is problematic as I must make my title images not have words or important images in the center.

**Comment by AntumDeluge** [comment]
Are you talking about the menu text on the opening screen?

**Comment by ghost** [comment]
I am.

**Comment by AntumDeluge** [comment]
I think [this might be the function](https://github.com/rpgboss/rpgboss/blob/894ba5f7d128b95a1633d5a55859e68c56625abf/core/src/main/resources/defaultrc/script/sys/start.js#L9) you are looking for. But, I haven't test it. Maybe try changing *game.CENTER()* to *game.LEFT()*

**Edit:** Yes, it would be nice if the editor had this option in the database menu.

**Comment by ghost** [comment]
Thank You

**Comment by AntumDeluge** [comment]
Did that work? If it's not implemented into the engine, I would keep this feature request open.

**Edit:** Nope. That just changes the justification of the text.
